### ISSUE TITLE
Add some more info to summer school page

### ISSUE THREAD

**Issue by jibarnum** [heliophysicsPy/heliophysicsPy.github.io#205]
We should make it clear that we expect a certain base level knowledge of Python (e..g, the basics, how to navigate a Jupyter notebook, etc.). Perhaps we can provide some links for learning about resources? For example, 

- For beginner Python material: https://astg606.github.io/py_courses/beginner_python/ (** I just checked and this actually contains a link to Jupyter notebook tutorials on the main page ! **). This resource was provided to me by Barbara Thompson.
- PlasmaPy's hackweek had some intro to Python materials here: https://hack.plasmapy.org/2021/python/ 
- Another intro to Jupyter notebooks: https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook 
- Links to Jupyter notebook and Python home pages?

**Comment by rstoneback** [comment]
There should be some good videos here from the scipy conference in Austin. 
https://www.youtube.com/results?search_query=scipy+2019

4hr Intro to Python https://www.youtube.com/watch?v=6KM8HOQi5Xk
Getting started with jupyter https://www.youtube.com/watch?v=RFabWieskak
numpy intro https://www.youtube.com/watch?v=ZB7BZMhfPgk
pandas intro https://www.youtube.com/watch?v=5rNu16O3YNE

I picked 2019 since there was an in person element. Other years work as well.

**Comment by jibarnum** [comment]
@rstoneback Those are EXCELLENT resources. Thank you!

**Comment by sapols** [comment]
PR open: https://github.com/heliophysicsPy/heliophysicsPy.github.io/pull/208
